---
networks:
  default:
    external: true
    name: proxynet

services:
  stash:
    container_name: stash
    image: stashapp/stash:latest
    restart: unless-stopped
    ports:
      - 9999:9999
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "2m"
    environment:
      STASH_STASH: /data/
      STASH_GENERATED: /generated/
      STASH_METADATA: /metadata/
      STASH_CACHE: /cache/
      STASH_PORT: 9999
    devices:
      - /dev/dri:/dev/dri
    command: /bin/sh -c "apk --no-cache add intel-media-driver && stash"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/store/media:/data
      - /mnt/store/containers/stash/config:/root/.stash
      - /mnt/store/containers/stash/metadata:/metadata
      - /mnt/store/containers/stash/cache:/cache
      - /mnt/store/containers/stash/blobs:/blobs
      - /mnt/store/containers/stash/generated:/generated
