version: "3.2"

networks:
  default:
    name: basket
    external: true

volumes:
  data:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=nas.home,rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14,nolock,soft,nfsvers=4"
      device: ":/volume1/data/"
  whisparr: {}
  cert: {}

services:
  whisparr:
    container_name: whisparr
    image: ghcr.io/hotio/whisparr:v3
    restart: unless-stopped
    logging:
      driver: json-file
    ports:
      - 16969:6969
      - 8008:8008
    environment:
      TZ: America/Los_Angeles
    volumes:
      - whisparr:/config
      - cert:/certs
      - data:/data
    labels:
      traefik.http.services.whisparr.loadbalancer.server.port: 6969
      traefik.http.routers.whisparr-http.entrypoints: web
      traefik.http.routers.whisparr-http.rule: Host(`whisparr.home`)
      traefik.http.routers.whisparr-https.entrypoints: websecure
      traefik.http.routers.whisparr-https.rule: Host(`whisparr.home`)
