---
networks:
  default:
    name: basket
    external: true

services:
  whisparr:
    container_name: whisparr
    image: ghcr.io/hotio/whisparr:v3
    restart: unless-stopped
    logging:
      driver: json-file
    ports:
      - 16969:6969
      - 8008:443
    environment:
      TZ: America/Los_Angeles
    volumes:
      - /mnt/syno_docker_nfs/whisparr/config:/config
      - /mnt/syno_docker_nfs/whisparr/certs:/certs
      - /mnt/syno_data_nfs:/data
    labels:
      traefik.http.services.whisparr.loadbalancer.server.port: 6969
      traefik.http.routers.whisparr-http.entrypoints: web
      traefik.http.routers.whisparr-http.rule: Host(`whisparr.home`)
      traefik.http.routers.whisparr-https.entrypoints: websecure
      traefik.http.routers.whisparr-https.rule: Host(`whisparr.home`)
      traefik.http.routers.whisparr-https.tls: true
