---
networks:
  default:
    external: true
    name: proxynet

services:
  whisparr:
    container_name: whisparr
    image: ghcr.io/hotio/whisparr:v3
    restart: unless-stopped
    logging:
      driver: json-file
    environment:
      PUID: 950
      PGID: 950
      UMASK: 002
      TZ: America/Los_Angeles
    hostname: whisparr
    volumes:
      - /mnt/store/containers/whisparr/config:/config
      - /mnt/store/containers/whisparr/certs:/certs
      - /mnt/store/media:/data
